### PR TITLE
sign

### PR DESCRIPTION
**Pull request by Kezii**

### CODE REVIEW

**Comment by cmd410** [comment]
@nukeop is it ok that the linked organization is literally empty here?

**Comment by Kezii** [comment]
yes it is, since
1) it exists since 2017
2) it's a public name that exists on some platforms and it's owned by me
3) I have not signed with my name, only the org

**Comment by cmd410** [comment]
@Kezii  Oh, okay then, but it kinda looks sus, hope no one creates dummy orgs just to put them on the list.

**Comment by Kezii** [comment]
There you go
immagine

**Pull request merged**
