### PR TITLE
Adding my signature.

### PR DESCRIPTION
**Pull request by eric-s-raymond**

### CODE REVIEW

**Comment by KOLANICH** [comment]
1. Please put a proof that it is your GH account to your website
2. Please, make your website available via correctly (ssllabs.com will help you) set up TLS of versions from 1.0 to 1.3.

**Comment by nukeop** [comment]
Thank you for all your software, and for your support. You're a true legend.

**Comment by shenlebantongying** [comment]
OMG! Its real!

 `:)`

**Comment by sildur** [comment]
>     1. Please put a proof that it is your GH account to your website
> 
>     2. Please, make your website available via correctly (ssllabs.com will help you) set up TLS of versions from 1.0 to 1.3.

Under which authority are you making such demands?

**Comment by KOLANICH** [comment]
It is not a demand (do you see the word `please`?), just the things that everyone understands are nice to have:
1. someone can try to discredit the initiative by creating fake accs of well-known people and getting their signatures merged, and then publicly claim that the initiative is fake fueled by "Russian bots"
2. Some people don't visit websites without TLS and are completely right, because lot of ISPs inject `<script>`s that can be considered malware into all HTML sent over unencrypted and unauthenticated HTTP.

**Comment by narodnik** [comment]
Respect

**Comment by Oxyd76** [comment]
Wow! It's real ESR! Thank You!

**Comment by sildur** [comment]
> It is not a demand (do you see the word `please`?), just the things that everyone understands are nice to have:
> 
>     1. someone can try to discredit the initiative by creating fake accs of well-known people and getting their signatures merged, and then publicly claim that the initiative is a fake fueled by "Russian bots". It'd be nice to have something tk debunk such claims.
> 
>     2. Some people don't visit websites without TLS and are completely right, because lot of ISPs inject `<script>`s that can be considered malware into all HTML sent over unencrypted and unauthenticated HTTP.

Yes, I have seen the word "please". As in " papers, please". Which is a demand. I have seen the tone. What I did not see is a "could you", for example. Or the bare minimal effort to check that the one doing the PR did not create his account just for this occasion, but it's an established account. 

It would be nice not to ask very specific people to upgrade their servers so some other people can be happy. Please.

**Comment by KOLANICH** [comment]
>What I did not see is a "could you", for example.

Fixed, thank you.

> Or the bare minimal effort to check that the one doing the PR did not create his account just for this occasion, but it's an established account.

In fact I has done some checks, such as visiting the repo of Westnoth and seeng ESR's contributions there and then reading about that fact in Wikipedia. But this is not a very strong proof.

>It would be nice not to ask very specific people to upgrade their servers so some other people can be happy. Please.

No, it wouldn't. Websites like homepages are created to allow visitors to visit them. So this wish sounds for me like

>It would be nice not to send issues into bug trackers of very specific people to fix bugs and implement features in their software so some other people can be happy. Please.

**Comment by sildur** [comment]
> > What I did not see is a "could you", for example.
> 
> Fixed, thank you.
> 
> > Or the bare minimal effort to check that the one doing the PR did not create his account just for this occasion, but it's an established account.
> 
> In fact I has done some checks, such as visiting the repo of Westnoth and seeng ESR's contributions there and then reading about that fact in Wikipedia. But this is not a very strong proof.
> 
> > It would be nice not to ask very specific people to upgrade their servers so some other people can be happy. Please.
> 
> No, it wouldn't. Websites like homepages are created to allow visitors to visit them. So this wish sounds for me like
> 
> > It would be nice not to send issues into bug trackers of very specific people to fix bugs and implement features in their software so some other people can be happy. Please.

I have edited my comment, because after reading it again, I did not like the tone. Hopefully is now more constructive.

**Comment by chinarulezzz** [comment]
> > It is not a demand (do you see the word `please`?), just the things that everyone understands are nice to have:
> > ```
> > 1. someone can try to discredit the initiative by creating fake accs of well-known people and getting their signatures merged, and then publicly claim that the initiative is a fake fueled by "Russian bots". It'd be nice to have something tk debunk such claims.
> > 
> > 2. Some people don't visit websites without TLS and are completely right, because lot of ISPs inject `<script>`s that can be considered malware into all HTML sent over unencrypted and unauthenticated HTTP.
> > ```
> 
> I have seen the word "please". As in " papers, please". Using the word "please" doesn't make something not look like a demand. The tone of the request does. What I did not see is a "could you", or even a "it would be nice", for example. Or the effort to check that the one doing the PR did not create his account just for this occasion, but it's an established account.
> 
> What it would have been nice is to create an issue in the repo to consistently handle well-known people signatures, instead of independently request ad-hoc identity verifications in PRs no one is going to see. It would be nice if you do that instead, please.

@sildur This is a subtle difference at the native speaker level. As a person for whom russian is a native language (as well as for @KOLANICH, I suppose), I did not take this as a demand at all. Thank you for clarifying. Without irony: thanks.

And yeah, @eric-s-raymond, wow!
Thank you, for all that you did. You've influenced my life so much with CatB. I wish you all the luck in the world, man!

**Pull request merged**
