### PR TITLE
Update README.md to include somewhat helpful visual instructions

### PR DESCRIPTION
**Pull request by IMSOASIAN**
I wanted to create some basic visual instructions to help somewhat non-tech savvy people. It just adds a new line that offers visual instructions. It's probably not needed at this point but it could be a vital resource for a person who learns visually and through examples.

### CODE REVIEW

**Comment by jobbautista9** [comment]
I think it would be a better idea to use a YouTube mirror for this.

**Comment by nukeop** [comment]
Can you link to invidious instead?

**Comment by IMSOASIAN** [comment]
@nukeop, can I instead put the actual file in the repo? I was thinking to put it under "_data"

**Comment by IMSOASIAN** [comment]
Never mind, I forgot there was a file limit

**Comment by IMSOASIAN** [comment]
Alright @nukeop, I've now included an Invidious mirror link. Is that alright?

**Comment by IMSOASIAN** [comment]
> Can you link to invidious instead?
I've done that now, did I do it correctly?

**Comment by nukeop** [comment]
Can you move this to the bottom of the section it's in?

**Comment by IMSOASIAN** [comment]
> Can you move this to the bottom of the section it's in?

Like this?

**Comment by nukeop** [comment]
Excellent, thanks

**Comment by imachug** [comment]
There's actually an easier way to sign, without forking.

1. Open https://github.com/rms-support-letter/rms-support-letter.github.io
2. Click _data
3. Click signed
4. Click Add file--Create new file
5. Type correct name and contents in
6. Press 'Propose new file'
7. Press 'Create pull request'

**Pull request merged**
