### PR TITLE
Create hard-sign.yaml

### PR DESCRIPTION
**Pull request by hard-sign**

### CODE REVIEW

**Comment by jobbautista9** [comment]
Can anyone who has a LinkedIn account verify if they are indeed Vladimir Komarov?

**Comment by hard-sign** [comment]
> Can anyone who has a LinkedIn account verify if they are indeed Vladimir Komarov?

You can ask anyone of my LinkedIn contacts.

**Comment by jobbautista9** [comment]
Please add your github profile on your LinkedIn contact info, so that I can verify.

**Comment by hard-sign** [comment]
Done. You can find the link in the contact info.

**Comment by jobbautista9** [comment]
Thanks! :D

**Pull request merged**
