### PR TITLE
Update davtur19.yaml

### PR DESCRIPTION
**Pull request by davtur19**
Changed the URL from GitHub to my website

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Hahaha, can you explain a bit for me what that link do?

Are you trying to count how much sticks-stuff 's highlighters visited your webste?

**Comment by shenlebantongying** [comment]
Ok, very cool `:)`

**Comment by davtur19** [comment]
image

nice, now i can see bad people in red

**Comment by shenlebantongying** [comment]
Don't share this, let herself frustrated :)

**Comment by davtur19** [comment]
https://github.com/sticks-stuff/highlight-RMS-supporters/blob/f707e42e7e403dcfa5d131f9ae5c11b434de028e/.github/workflows/workflow.yml#L29

I can't belive it

**Comment by shenlebantongying** [comment]
LMAO!

**Pull request merged**
