### PR TITLE
Create nlocalhost.yml

### PR DESCRIPTION
**Pull request by nikitalocalhost**

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Thanks!

**Comment by hexherhide666** [comment]
> 
>your coming to get jackson today what time

**Comment by hexherhide666** [comment]
aren't you?

**Comment by shenlebantongying** [comment]
@hexherhide666 What do you mean?

**Comment by hexherhide666** [comment]
are you going to come get him so he don't die I'm getting ready to go please come get him

**Pull request merged**
