### PR TITLE
Create atererus.yaml

### PR DESCRIPTION
**Pull request by atererus**

### CODE REVIEW

**Review by jobbautista9 — CHANGES_REQUESTED** [review]
Thanks for stating your reason for signing! But please follow the proper yaml format. You can put your reasons either in this PR, or as a commit message instead.

**Comment by nukeop** [comment]
Please don't add content other than your signature.

**Comment by jobbautista9** [comment]
Feel free to reopen or create a new PR once you've followed the proper yaml format.

**Comment by atererus** [comment]
Done ... ?  ... I'm new to this

**Comment by nukeop** [comment]
Could you edit your entry to only include your signature?

**Comment by atererus** [comment]
What is my signature? I edited the entry just to contain name: and link: just as the instructions said. Probably that is what you mean? And I think it is already in the master. I deleted the fork.

**Pull request closed without merging**
