### PR TITLE
Improved the open letter for Japanese translation

### PR DESCRIPTION
**Pull request by taiju**
There may be parts where the previous translation was better, so it would be helpful if you could check it thoroughly.

### CODE REVIEW

**Comment by imachug** [comment]
cc @ChanoSan

**Comment by ChanoSan** [comment]
In large part it seems good to me, but there are three places I'd like to suggest slight edits:

On Line 16, change `最近、彼が個人的な意見を述べたことで、FSF の理事会から彼を外そうとする卑劣なオンライン攻撃がありました` to `最近、ストールマンさんが個人的な意見を述べたことで、FSF の理事会から彼を外そうとする卑劣なオンライン攻撃がありました`

I may be overly finicky, but I think stating "Mr. Stallman" as the subject of this sentence makes the sentence clearer and gives it more emphasis, rather than reverting to "he" this early in the letter.

On Line 28, change `それはさておき、迫害を受けている、かの件のストールマンの意見は、FSF のようなコミュニティを率いる能力とは関係がありません` to `それはさておき、ストールマンさんが迫害を受けてきた意見はFSFのような コミュニティーを主導する彼の資格と関係がありません`

The sentence you constructed is cleaner than mine in terms of overall grammar, but I just wanted to rework the section about "opinions over which he has received criticism" to flow a little smoother. I'm open to criticism on my structure here, though, it's a difficult grammar for me to parse even on a good day, lol

On Line 39, change `あなたたちは、いかなるコミュニティのリーダーの選択にも関与できません` to `あなたたちは、いかなるコミュニティのリーダーの選択において関与していません`

I feel like 選択にも関与できません (cannot play a role) sounds too much like "are not able to" rather than "do not have a right to/have no place in", so I think 選択において関与していません carries that nuance better. But again, I may be missing a grammatical nuance myself, so I won't carve that in stone.

**Comment by taiju** [comment]
@ChanoSan Thanks for the review. Basically, I'm trying to reflect the points you made, but I have one point to discuss.
In the proposed translation, Stallman is simply written as `ストールマン`. Would it be better to replace the whole thing with `ストールマン氏` or `ストールマンさん`?

**Comment by ChanoSan** [comment]
> @ChanoSan Thanks for the review. Basically, I'm trying to reflect the points you made, but I have one point to discuss.
> In the proposed translation, Stallman is simply written as `ストールマン`. Would it be better to replace the whole thing with `ストールマン氏` or `ストールマンさん`?

Ahh... this one's always difficult for me. Proper titles and naming conventions are my weak point.
I feel like if we stick with one for the entire letter, maybe ストールマン氏 sounds better?

**Comment by taiju** [comment]
@ChanoSan Since it is a letter, `Mr. Stallman` might be more appropriate. I will fix it tomorrow, including the other issues.  `README_JP.md` as well.

**Comment by taiju** [comment]
@ChanoSan @imachug Corrected points raised.
It might be better to fix the [image file](https://github.com/rms-support-letter/rms-support-letter.github.io/blob/master/assets/social-media-preview_ja_JP.png) to `リチャード・M・ストールマン氏` as well, but I didn't know how to fix it.

**Comment by imachug** [comment]
There's a source here: https://github.com/rms-support-letter/rms-support-letter.github.io/files/6205876/rms-design-source-v2.zip

**Comment by taiju** [comment]
@imachug Thanks!

**Comment by taiju** [comment]
Hmm, I've started editing SVG in Emacs, but it looks like I'd better install InkScape.
I also thought it would be better to ask @ChanoSan to help me with the images for Japanese, since they seem to have already been adjusted for font size and position.

**Comment by taiju** [comment]
@ChanoSan I tried to fix it here, but it looks a little different. Is it good?

test

**Comment by ChanoSan** [comment]
I think it looks fine, if @imachug is good with it.

**Comment by taiju** [comment]
@ChanoSan Thanks! Can I replace the image as well? I'm not committed yet.

**Comment by imachug** [comment]
I'm OK with the image and the translation from a stylistic point of view (sadly I don't know Japanese).

**Comment by taiju** [comment]
@ChanoSan @imachug OK. It's almost time for me to go to bed, so I'll commit, but if there are any problems, I'd appreciate it if you could revert commit.

**Comment by taiju** [comment]
Commited.

**Comment by imachug** [comment]
Merging for now

**Pull request merged**
