### PR TITLE
Update dzhigit1.yaml

### PR DESCRIPTION
**Pull request by dzhigit1**
Recently joined. #3867

### CODE REVIEW

**Comment by 6r1d** [comment]
Thank you, I appreciate your help with FSF :-)

**Comment by nukeop** [comment]
@dzhigit1 We've noticed that you added several people to the letter, are you representing them?

**Comment by dzhigit1** [comment]
#3105 #3114 @nukeop

**Comment by dzhigit1** [comment]
They were sent through email.

**Comment by nukeop** [comment]
Ok, thank you for clarifying.

**Pull request merged**
