### PR TITLE
Create chunfeng_tsin.yaml

### PR DESCRIPTION
**Pull request by TsinElisha**

### CODE REVIEW

**Comment by 6r1d** [comment]
Thanks for your support. Your link doesn't appear to work, does it? If not, GitHub URL is ok. :-)

**Comment by TsinElisha** [comment]
Yes, but it will be work soon.

**Comment by 6r1d** [comment]
Alright, merging, thanks again!

**Comment by TsinElisha** [comment]
You're welcome, we should stand together to defend some precious things.

**Pull request merged**
