### PR TITLE
Improve Romanian translations.

### PR DESCRIPTION
**Pull request by brown121407**
Add diacritics, fix some verb conjugations and typos and adapt some
expressions to better fit the language.

### CODE REVIEW

**Review by cristeigabriel — APPROVED** [review]

**Review by cristeigabriel — CHANGES_REQUESTED** [review]
Trailing whitespace in index la linia 52

**Comment by brown121407** [comment]
@cristeigabriel, I can't see any trailing whitespace on line 52 in index_ro.md (or on any line of that file, really). I looked with whitespace-mode in Emacs. Maybe you are referring to the double space after the dot on that line?

**Comment by cristeigabriel** [comment]
Yes, I've looked now in full screen, it's actually a double space.

**Comment by imachug** [comment]
Thanks!

**Pull request merged**
