### PR TITLE
Create mario.yaml

### PR DESCRIPTION
**Pull request by Padreeno**

### CODE REVIEW

**Comment by jobbautista9** [comment]
Hmm, sorry, can you tell us more about yourself? Just wanted to make sure you're a real person.

**Comment by Padreeno** [comment]
Hi Job

Sure.
I'm the founder and the CEO from BillCare https//www.billcare.ch.
In our company we try to use as much open source software as possible.

The developer https://github.com/n3w  brought me to open source philosphy, which I support since 2018.

Our company uses the project https://github.com/metasfresh in the health care sector in Switzerland around the billing / invoicing service.
I am the project manager, which gives orders to metas GmbH for further development.

Kind regards
Mario

**Comment by jobbautista9** [comment]
Ok, thanks for signing! :D

**Comment by Padreeno** [comment]
:)

**Pull request merged**
