### PR TITLE
Create Georg Lehmann.yaml

### PR DESCRIPTION
**Pull request by GeorgLLehmann**

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Thanks!

**Comment by GeorgLLehmann** [comment]
I did forget something. I'm member of the FSF.

**Comment by shenlebantongying** [comment]
@GeorgLLehmann can you add via another PR ? 

`:)`

**Comment by shenlebantongying** [comment]
@GeorgLLehmann I add that in https://github.com/rms-support-letter/rms-support-letter.github.io/commit/8fa170ed6fd6e0b835d3a7e3afc22cf643825ad2

Is it looks ok?

**Pull request merged**
