### PR TITLE
Added hreflang

### PR DESCRIPTION
**Pull request by taiju**
Added hreflang so that Google can crawl multilingual support effectively.

I tried to respect the language and not limit the region, because to reach a wide range of users, but I am a little lost. For example, for English, I specified `en` instead of `en-US`. (However, the flag emoji is the United States.)

This is a proposal, so I'll leave it to you to decide.

ref:
https://developers.google.com/search/docs/advanced/crawling/localized-versions
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

### CODE REVIEW

**Comment by shenlebantongying** [comment]
@nukeop

**Comment by imachug** [comment]
OK for now but the list should be generated automatically

**Comment by imachug** [comment]
Nah, I'm an idealist :)

**Comment by shenlebantongying** [comment]
Too real :)
https://lists.gnu.org/archive/html/emacs-devel/2018-03/msg00089.html
image

**Comment by taiju** [comment]
It is better to generate them from the file names, but some of them are incompatible with ISO 639-1.
For example, the Albanian language uses `al` for file names, but the ISO 639-1 notation is `sq`.

**Comment by taiju** [comment]
Correction, it is better to generate it from the Front Matter locale. However, it is difficult to automate the process if the file names are not consistent.

**Comment by imachug** [comment]
> It is better to generate them from the file names, but some of them are incompatible with ISO 639-1.

There's `locale` field in the pages headers.

**Comment by taiju** [comment]
Yes, as I corrected earlier, I also thought it would be better to base it on the `locale` field in the header (the `locale` field in Front Matter). 

Front Matter https://jekyllrb.com/docs/front-matter/

**Comment by imachug** [comment]
Oh, sorry, I had no idea it's called Front Matter.

**Comment by taiju** [comment]
Sorry for the lack of explanation here as well :bow:

I'll try to automate the process tomorrow, along with fixing the file name, as it will be troublesome to manage.

**Pull request merged**
