### PR TITLE
Create thatonecalculator.yaml

### PR DESCRIPTION
**Pull request by ThatOneCalculator**

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Sorry about the misname, I fixed it

**Comment by 6r1d** [comment]
Thank you for your support! 
Do you mind using a real name for improving the letter's credibility? If not, it's your choice. You can add it in another PR. :-)

**Comment by ThatOneCalculator** [comment]
> Thank you for your support!
> Do you mind using a real name for improving the letter's credibility? If not, it's your choice. You can add it in another PR. :-)

I'd rather not put my real name.

**Comment by 6r1d** [comment]
Understood.

**Pull request merged**
