### PR TITLE
Fix gramatical error in german version

### PR DESCRIPTION
**Pull request by Effiti**

### CODE REVIEW

**Comment by shenlebantongying** [comment]
I don't understand German, so I will trust you.
Thx

**Comment by backenddeveloper** [comment]
Genuine question: Is this a gender equality thing or a common terminology thing?

**Comment by Effiti** [comment]
It's a grammatical error, has nothing to do with gender equality

**Comment by backenddeveloper** [comment]
So what is Cython in this context then...? 😂

**Comment by Effiti** [comment]
English xD

**Pull request merged**
