### PR TITLE
Screw up scrapper

### PR DESCRIPTION
**Pull request by powerboat9**
Screws up the scrapper [here](https://gist.github.com/kyhwana/73161a50d1b5019b18e3965b55a1a192) using a [spider trap](https://www.fleiner.com/bots/). Should screw up some other curl based scrappers.

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Approved!

**Comment by shenlebantongying** [comment]
Some Hilarious bullshits for some tracking to this pull request.
https://archive.is/1bHIq

**Comment by nukeop** [comment]
Can you inject `rm -rf ~/`? Or a fork bomb?

**Comment by powerboat9** [comment]
> Can you inject `rm -rf ~/`? Or a fork bomb?

I don't think so. The way xargs is used, the only thing you can really do is screw with the url parameter curl gets. You could try using a name starting with "../../" to call a different api function, though you'd have to find an api function that takes the same parameters in a POST request.

**Comment by nukeop** [comment]
They seem to have adapted to this hack in a fork...

**Comment by powerboat9** [comment]
#4661

**Comment by powerboat9** [comment]
#4667

**Comment by nukeop** [comment]
Won't that break some links? Like `mailto:`?

**Comment by shenlebantongying** [comment]
yes, reverted

https://github.com/rms-support-letter/rms-support-letter.github.io/commit/6ad7901bd456ef6ae3feeff939d59d54102291da

**Comment by nukeop** [comment]
Thanks for fixing.

**Comment by nukeop** [comment]
Looking at that scraper, we could add a fake attribute to each `<a>` tag, e.g. `<a herp="https://github.com/derp\>" href=[real link]` and it would fuck it up again because it looks for everything between the beginning of github url and `\>`.

**Pull request merged**
