### PR TITLE
Sign

### PR DESCRIPTION
**Pull request by owl4ce**

### CODE REVIEW

**Comment by toriningen** [comment]
Your name has been used in anti-RMS campaign list of signatures (https://rms-open-letter.github.io/), you might want to bring this up and make them liable for faking signatures.

**Comment by imachug** [comment]
They signed that letter too: https://github.com/rms-open-letter/rms-open-letter.github.io/pull/1589

**Comment by owl4ce** [comment]
Sorry, that was my mistake while reading. Can I pull my name from that repo? 😢

**Comment by imachug** [comment]
Yes, you can. Open a new PR on their repo with your signature removed.

**Pull request merged**
