### PR TITLE
signed

### PR DESCRIPTION
**Pull request by o7hYt**
Yes, I support stallman cause I don't care for his philoshopical arguments, I look his programmer side while choosing him to be in fsf, thats the most logical argument. I don't even believe there's a need for this, rms is the free software foundation himslef.

### CODE REVIEW

**Review by jobbautista9 — CHANGES_REQUESTED** [review]
It'd be better if you rename the file into o7hYt.yaml, so that it's easier to differentiate signatures.

**Comment by o7hYt** [comment]
and done

**Comment by o7hYt** [comment]
done

**Review by jobbautista9 — APPROVED** [review]
LGTM

**Pull request merged**
