### PR TITLE
Structure that makes more sense

### PR DESCRIPTION
**Pull request by cmd410**
Just a cosmetic fix of project structure. Does the same thing, but more organized.

- `index.md` - is just a letter itself(`index.html` is removed)
- `_layouts/signed.html` - template that displays signatures(used by `index.md`)
- plus, used ordered list for signatures, so it's easy to count them

**This overwrites `index.md`**, so this probably should be merged **AFTER** you are done with merging PRs there.

### CODE REVIEW

**Comment by nukeop** [comment]
Thanks, this looks great, you saved a lot of time already. Counting signatories will be necessary as we're overtaking the other open letter now.

**Comment by evrial** [comment]
Just merge this already because people are idiots.

**Comment by nukeop** [comment]
We're almost ready to merge this. Just need to convert signatures

**Comment by nukeop** [comment]
Here's hoping I ddin't break anything

**Comment by evrial** [comment]
Looks good, sorting is funny

**Pull request merged**
