### PR TITLE
Update check-signatures-format.py

### PR DESCRIPTION
**Pull request by shenlebantongying**
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/2895

### CODE REVIEW

**Comment by imachug** [comment]
Put on hold, please ping me if I don't reply within 4 hours

**Comment by gorshunovr** [comment]
@shenlebantongying confirm that it allows files with 2 lines (without blank line at the end of file), and then it urgently needs to be merged.

**Comment by gorshunovr** [comment]
@nukeop highlighting issue with files consisting of 2 lines only, without blank line at the end. ^^^

**Comment by nukeop** [comment]
I don't see any problems if there are no blank lines.

**Comment by gorshunovr** [comment]
For example, #2923 does not pass automated checks because it's 2 lines, instead of 3. This distracts those who submit signatures. Please, address this issue.

**Comment by imachug** [comment]
No, it doesn't pass because of whitespace after the name.

**Comment by gorshunovr** [comment]
Hmmm... Then we need to explicitly specify what is wrong in error message.

We also have a lot of unmerged PRs which did not pass checks and have been closed by authors only because of that. Example: #2969.
List of PRs: https://github.com/rms-support-letter/rms-support-letter.github.io/pulls?q=is%3Apr+is%3Aclosed+is%3Aunmerged

**Comment by imachug** [comment]
Fixed in d05998f33b346ecef22dd0e1820987b72a61ce39.

**Pull request closed without merging**
