### PR TITLE
Sign

### PR DESCRIPTION
**Pull request by pavel-zhigulin**

### CODE REVIEW

**Comment by podvornyakva** [comment]
Please. add a file instead of edit index.md

Follow README.md instructions.

Thank you.

**Comment by imachug** [comment]
Merged manually.

**Comment by pavel-zhigulin** [comment]
@podvornyakva there was other README.md instructions when I was creating this PR. Sorry.
@imachug thank you for your help.

**Comment by podvornyakva** [comment]
> Sorry.

Ты не виноват. Просто были проблемы с конфликтами коммитов. По-этому изменили способ.

**Pull request closed without merging**
