### PR TITLE
Create BryanLunduke.yaml

### PR DESCRIPTION
**Pull request by BryanLunduke**
name: Bryan Lunduke (Formerly: Deputy Editor of Linux Journal, Linux Marketing at SUSE, Marketing Director at Purism, Tech Journalist at Network World, VP of Tech at various firms)
link: https://lunduke.com

### CODE REVIEW

**Comment by homeless-schizo-retard** [comment]
B A S E D

**Comment by ExtReMLapin** [comment]
BASED

**Comment by josephbburg** [comment]
Thank you friend

**Comment by Motophan** [comment]
B to the A to the S to the E to the D
And purism corebootpilled

**Comment by 6r1d** [comment]
I'm glad to see you are with us. Thank you for your videos, you've helped support Richard a lot!

**Pull request merged**
