### PR TITLE
Add Persian translation

### PR DESCRIPTION
**Pull request by ahangarha**

### CODE REVIEW

**Review by spacepilotAV — APPROVED** [review]
Looks good.

**Comment by imachug** [comment]
Amazing, thanks!

**Comment by trufanov-nok** [comment]
@imachug ok, but now we need a link to this page in _layouts/signed.html

**Comment by trufanov-nok** [comment]
Hey Mostafa,
Could you please check your translation page:  https://rms-support-letter.github.io/index_fa.html
And make sure it looks like expected. Please make adjustments to index_fa.md file if needed. I suspect my browser doesn't render this page correctly (links..) bcs of rtl language.

**Pull request merged**
