### PR TITLE
Richard Stallman Support.yaml

### PR DESCRIPTION
**Pull request by vagabundoscuro**
Richard Stallman has my support.

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Can u please edit the file in this format?

```
name: <your name here (optional organization or company)>
link: <link to your profile or site>
```

**Comment by hexherhide666** [comment]
okie dokie

**Comment by zeustroyano** [comment]
https://github.com/rms-support-letter/rms-support-letter.github.io/issues/4101

**Comment by nikodis** [comment]
Name: nikodis
Link: www.umc.edu.ve

**Comment by shenlebantongying** [comment]
@nikodis if you want to sign, pls go here -> https://github.com/rms-support-letter/rms-support-letter.github.io/issues/837

This is another person's pull request.

**Comment by lionelPhaeton** [comment]
I support Richard Stallman.

**Comment by shenlebantongying** [comment]
Duplicate ofhttps://github.com/rms-support-letter/rms-support-letter.github.io/pull/4212

**Pull request closed without merging**
