### PR TITLE
Add JP translation

### PR DESCRIPTION
**Pull request by ChanoSan**

### CODE REVIEW

**Comment by imachug** [comment]
Thanks!

**Comment by shenlebantongying** [comment]
@ChanoSan I think you also have to add an emoji icon for it
https://github.com/rms-support-letter/rms-support-letter.github.io/blob/master/_includes/translations.html
image

**Comment by imachug** [comment]
Please don't--this is being automated right now.

**Comment by shenlebantongying** [comment]
ok, NVM

**Comment by ChanoSan** [comment]
I added a flag emoji to /_layouts/signed.html from my own fork, but it looks like things changed between my last update and this PR, because it looks like its in /_includes/translations.html 

Is that something you can do on your end, or should I make another PR with the correct modifications?

**Comment by imachug** [comment]
I'll do that myself.

**Comment by shenlebantongying** [comment]
@ChanoSan It should works now

image

**Comment by imachug** [comment]
Yup, we automated that.

**Pull request merged**
