### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by glolsh**

### CODE REVIEW

**Comment by podvornyakva** [comment]
Please. add a file instead of edit index.md

Follow README.md instructions.

Thank you.

**Comment by imachug** [comment]
Merged manually.

**Comment by glolsh** [comment]
> Please. add a file instead of edit index.md
> 
> Follow README.md instructions.
> 
> Thank you.

Sorry, got no notifications about your comment

**Comment by glolsh** [comment]
> Merged manually.

Thank you

**Pull request closed without merging**
