### PR TITLE
Added russian translation of README.md

### PR DESCRIPTION
**Pull request by teamfighter**
Added russian translation of README.md

### CODE REVIEW

**Comment by gorshunovr** [comment]
Thank you for you PR! Please, contribute to #1808 which has been submitted earlier.

**Comment by teamfighter** [comment]
@gorshunovr WIP
https://github.com/HardDie/rms-support-letter.github.io/pull/1

**Comment by nukeop** [comment]
Sorry, I merged the other one since it was first.

**Comment by teamfighter** [comment]
np

**Pull request closed without merging**
