### PR TITLE
Create radiwick.yaml

### PR DESCRIPTION
**Pull request by radiwick**

### CODE REVIEW

**Review by jobbautista9 — CHANGES_REQUESTED** [review]
Same issue as #4426

**Comment by imachug** [comment]
You need something along the lines of

```
name: radiwick
link: https://github.com/radiwick
```

...to the file. I encourage you to use your real name after `name:` though.

**Review by jobbautista9 — APPROVED** [review]
Ah, I misunderstood! You're trying to remove yourself from the signatures. I apologize.

**Comment by imachug** [comment]
No, they are not. I added them from email just a few minutes ago

**Review by jobbautista9 — COMMENTED** [review]
Okay, I'm confused now. The current file on the repo is imported from mail. I think the appropriate resolution is to close this PR.

@radiwick If you want to remove your signature, please be clear about it by deleting it. Thanks

**Pull request closed without merging**
