### PR TITLE
Add social media preview picture

### PR DESCRIPTION
**Pull request by gorshunovr**
Added social media preview picture and removed unnecessary spaces at the end of some lines.

Closes: #1732

### CODE REVIEW

**Comment by nukeop** [comment]
A bit too colorful to be truly representative, we need something more "designed" and muted.

**Comment by gorshunovr** [comment]
I fully agree, but unfortunately I've reached the maximum of my design skills here.

**Comment by nukeop** [comment]
I'll try to whip up something when I'm finished with work

**Comment by imachug** [comment]
I'll convert the PR to draft then

**Comment by zezic** [comment]
rms-design-green-v2
You can use the picture I just designed if you think it's better. I'm ready to discussion here or in the issue #1732 if any changes are needed!

**Comment by nukeop** [comment]
This looks great, I will add it to the repo

**Comment by nukeop** [comment]
@gorshunovr Can you use this image please?

**Comment by imachug** [comment]
Merged.

**Comment by nukeop** [comment]
https://socialsharepreview.com/?url=https://rms-support-letter.github.io/

Doesn't work apparently (yet)

**Comment by gorshunovr** [comment]
Works now. Thanks, @nukeop @zezic.

**Pull request closed without merging**
