### PR TITLE
Anatoly Tsypkov.yaml

### PR DESCRIPTION
**Pull request by libered**

### CODE REVIEW

**Comment by 6r1d** [comment]
Hello. Please check a proper `.yaml` and data format in the `README.md` file.
https://github.com/rms-support-letter/rms-support-letter.github.io

**Review by jobbautista9 — CHANGES_REQUESTED** [review]
Please follow the proper yaml format.

**Comment by 6r1d** [comment]
Try this:

```yaml
name: Anatoly Tsypkov
link: https://github.com/libered
```

**Comment by jobbautista9** [comment]
Don't forget to add the .yaml extension to your filename.

**Comment by libered** [comment]
name: Anatoly Tsypkov
link: https://github.com/libered

**Pull request merged**
