### PR TITLE
Create megyei.yaml

### PR DESCRIPTION
**Pull request by megyei**

### CODE REVIEW

**Comment by megyei** [comment]
Supprt RMS

**Comment by 6r1d** [comment]
Hello. Could you please share any more details about yourself, so we can confirm you are a real person?

**Comment by megyei** [comment]
Hi,

I'm a real person of nearly the same age as rms.
I'm leaving in Munich, Germany and have been using Emacs for 30 years.

Once I contributed a small patch of a Makefile in Emacs and am still 
listed in etc/AUTHORS:
etc/AUTHORS:3333:Mathias Megyei: changed lisp/Makefile.in
lisp/ChangeLog.12:13222:2006-02-08  Mathias Megyei 
***@***.***>  (tiny change)

Best Regards,

Mathias

**Comment by 6r1d** [comment]
Thanks for the provided details and for your support! :-)

**Pull request merged**
