### PR TITLE
Add signature of @SeraphimRP.

### PR DESCRIPTION
**Pull request by SeraphimRP**
Thanks.

### CODE REVIEW

**Comment by Aspie96** [comment]
Hi, @SeraphimRP.

If I may ask, what made you change your mind?

**Comment by SeraphimRP** [comment]
> 
> 
> Hi, @SeraphimRP.
> 
> If I may ask, what made you change your mind?

I'm an Orthodox Christian. The statements made by RMS after the controversy indicate that he's acknowledged his errors. I can respect that. Even if the errors weren't recanted - I still would've at least withdrawn my signature from the condemnation letter given the excessive demands and measures taken by that project.

This isn't to say that RMS is going to be better or that there won't be incidents like this in the future, but at this time I see humility.

**Comment by Aspie96** [comment]
Thanks

**Comment by 6r1d** [comment]
> I still would've at least withdrawn my signature from the condemnation letter given the excessive demands and measures taken by that project.

I'd like to thank you as well, @SeraphimRP, I feel much better when I see people are thoughtful about others. This is a good approach!

**Pull request merged**
