### PR TITLE
Armenian translation

### PR DESCRIPTION
**Pull request by appetrosyan**
Should address the first part of #3991.

### CODE REVIEW

**Comment by jobbautista9** [comment]
Google doesn't translate Armenian well, it seems. I will need some help from another native Armenian speaker.

**Comment by appetrosyan** [comment]
@jobbautista9 Google is an ML-based translation engine, it has a habit of adding things that often follow in newspapers. This is a hand translation. I'm looking for people in my immediate vicinity that could help with double-checking the translation.

**Comment by jobbautista9** [comment]
Ok, I've also asked for help in IRC, Matrix, and Discord, if that helps. Someone in IRC said they know someone who speaks Armenian somewhat.

**Comment by appetrosyan** [comment]
A friend of mine also agreed to help (and maybe sign), but only in 7 hours or so.

**Comment by jobbautista9** [comment]
Since the translation of index.md is not yet done, I've marked this PR as a draft for now. Feel free to mark as ready when you're done translating.

**Comment by appetrosyan** [comment]
AFAIK, I'm supposed to create a file with the right localisation in `_localisations`.

**Comment by jobbautista9** [comment]
Ah yes, I missed those commits, thanks for marking the PR as ready.

**Comment by shenlebantongying** [comment]
If we cannot find a reviewer, I think we better just merge it.

Once it got wider audiences, someone else would correct mistakes.

**Comment by shenlebantongying** [comment]
It looks good.
image

**Pull request merged**
