### PR TITLE
Create Kotoess.yaml

### PR DESCRIPTION
**Pull request by Kotoess**

### CODE REVIEW

**Comment by jobbautista9** [comment]
Please make your VK profile public, or use another public profile (like your github). Thanks!

**Comment by shenlebantongying** [comment]
We can track the sign to the pull request, so as long as their GitHub account is valid, just merge it.

**Comment by Kotoess** [comment]
Ok

**Comment by 6r1d** [comment]
Thank you for your support! Please consider sharing this letter on the social media.

**Pull request merged**
