### PR TITLE
Free to RSM

### PR DESCRIPTION
**Pull request by FloMko**
There is no room for freedom in such unjust situation!
RSM is a person with a modern view and a strong will
There is a shame to people/company that support hype, not a IRL things

### CODE REVIEW

**Comment by 6r1d** [comment]
Thank you for your support! Please add a `.yaml` extension to your file. I can't for some reason.

**Review by jobbautista9 — CHANGES_REQUESTED** [review]
Please append a .yaml extension on the end of your filename.

**Comment by jobbautista9** [comment]
Also, please add a link to your github on your LinkedIn contact info so that I can verify that you are that LinkedIn profile.

**Comment by 6r1d** [comment]
Thank you for your support! Please consider sharing this letter on the social media.

**Pull request merged**
