### PR TITLE
Fix punctuation in Russian translation

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Do those punctuations have no meaning in Russian?

**Comment by shenlebantongying** [comment]
@imachug

**Comment by shenlebantongying** [comment]
Thanks!

**Comment by DarthGandalf** [comment]
> Do those punctuations have no meaning in Russian?

There are rules when to add commas and when not to. In these 2 sentences there is no grammatical reason to have a comma in these places.

**Comment by shenlebantongying** [comment]
ok, thanks

**Comment by imachug** [comment]
Just for the record LGTM

**Pull request merged**
