### PR TITLE
Better translation workflow(imo)

### PR DESCRIPTION
**Pull request by cmd410**
So, kinda new, more structural workflow for translations.

Write translation to `_translation/index_lang.md` where `lang` is a language code, add `emoji` attribute, and voila, it's shown on the page and available under `/index-lang.html` link, no other modifications required.

1. Unclutters root directory
2. Simplifies adding links to translations
3. Avoids merge conflicts when several translations add link to the same line

Example `_translations/index_de.md`:
```md
---
layout: signed
title: An open letter in support of Richard M. Stallman
description: An open letter in support of Richard Matthew Stallman being reinstated by the Free Software Foundation
image: /assets/social-media-preview.png
locale: de_DE
twitter:
  card: summary_large_image
emoji: 🇩🇪
---

2021-03-23

Richard M. Stallman, ...
```

Also, added translation contributing guidelines.

### CODE REVIEW

**Comment by nukeop** [comment]
I think the last PR currently on the list includes a switch from emoji to an image font, and I feel this will be incomaptible with your changes. however, I think your PR will make translations a lot easier, so I'm going to merge it. Do you want to resolve the conflicts yourself? Or should I do it?

**Comment by cmd410** [comment]
I don't feel qualified enough to resolve conflicts. Honestly, have no idea how to do it )

**Comment by cmd410** [comment]
@nukeop  btw, doesn't `_includes/translations.html` use emojis right now? Or what do you mean by `switch from emoji to an image font`?

**Comment by nukeop** [comment]
It does now, but I meant this: #2717 

And there are some translations (e.g. Latvian) in the pipes that will need to be converted.

**Comment by nukeop** [comment]
Ok, I will resolve conflicts now

**Comment by cmd410** [comment]
Wait, the layout i removed was actually needed, I will revert it now

**Comment by cmd410** [comment]
Now, ready for merge

**Comment by nukeop** [comment]
I merged your changes, but it has the side effect of not recognizing this pull request as merged. They're on master though.

**Comment by cmd410** [comment]
@nukeop yeah, I see, now need to move remaining translations from root and add emojis to them

**Comment by RealJTG** [comment]
@nukeop 
> a switch from emoji to an image font, and I feel this will be incomaptible with your changes

Depends on how `jemoji` plugin process placeholders here https://github.com/rms-support-letter/rms-support-letter.github.io/pull/3009/files#diff-84661dd2684f56f27dade19f9b8876c369c724d60994d977447ef92108f8077fR5 - before template render or after.

I'll dig this further, I think pictures+alt text are still better choice.

**Comment by cmd410** [comment]
@RealJTG I think it's no problem to resolve conflicts by simply using `:this_notation:` instead of emojis

**Comment by shenlebantongying** [comment]
@cmd410 I think we got a little problem now, we have too much translations that china got isolated due to line spacing.

image

**Comment by cmd410** [comment]
@shenlebantongying Wow, that's unexpected... Can probably be fixed with template that limits amount of translations per line:/

**Comment by shenlebantongying** [comment]
@cmd410  I think we can just change line at flag 10, so that no one got isolated.

https://github.com/rms-support-letter/rms-support-letter.github.io/pull/3052

**Pull request closed without merging**
