### PR TITLE
Add JP social media image to /assets, edit /_translations/index_jp.md to link to it

### PR DESCRIPTION
**Pull request by ChanoSan**

### CODE REVIEW

**Comment by imachug** [comment]
I don't like that the text was moved very much to the left and it's no longer aligned with header. Do you know if you can fix that?

**Comment by ChanoSan** [comment]
I shunted it over because Stallman's name was starting to cover his face. I can play with the font and size to try and get it back, let me fiddle with Inkscape a bit

**Comment by ChanoSan** [comment]
I adjusted the font sizes so it stays in the same alignment as the EN image, also fixed the naming convention to social-media-preview_ja_JP

**Comment by imachug** [comment]
Great, thanks a lot!

**Pull request merged**
