### PR TITLE
Create index_gr.md

### PR DESCRIPTION
**Pull request by eohon**
This is the Greek translation for the index text.

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Thats looks great.

However, can you please add some headings like other translations.

Its used for generate icon and titles

image

**Comment by eohon** [comment]
@shenlebantongying 
Sorry about that. I think I added what you asked. Let me know if there's anything else.

**Comment by shenlebantongying** [comment]
It looks great! Thank you.

**Comment by shenlebantongying** [comment]
It works
image

**Pull request merged**
