### PR TITLE
Signing

### PR DESCRIPTION
**Pull request by RealGithubAdmin**

### CODE REVIEW

**Comment by imachug** [comment]
Can you prove you're the real admin? :)

**Comment by cristeigabriel** [comment]
> Can you prove you're the real admin? :)

It's in his name, man!

**Comment by RealGithubAdmin** [comment]
I'm the real Github Admin

**Comment by imachug** [comment]
Post that from Nat's account please then I'll believe you

**Comment by RealGithubAdmin** [comment]
Nat is below me in the company hierarchy. His post means nothing.

**Comment by imachug** [comment]
If you're the boss, you can ask Nat to do you a small favor

**Pull request closed without merging**
