### PR TITLE
Add signature

### PR DESCRIPTION
**Pull request by rs-blashyrkh**

### CODE REVIEW

**Comment by podvornyakva** [comment]
Please. add a file instead of edit index.md

Follow README.md instructions.

Thank you.

**Comment by rs-blashyrkh** [comment]
Should I revert my changes made to index.md or leave them as is? Should I issue new pull request or edit this one?

**Comment by imachug** [comment]
Merged manually.

**Comment by rs-blashyrkh** [comment]
Thanks. I appreciate your work, good luck!

**Pull request closed without merging**
