### PR TITLE
My signed

### PR DESCRIPTION
**Pull request by Mehavoid**

### CODE REVIEW

**Comment by toriningen** [comment]
Your name has been used in anti-RMS campaign list of signatures (https://rms-open-letter.github.io/), you might want to bring this up and make them liable for faking signatures.

**Comment by Mehavoid** [comment]
@toriningen I revised my view after signing, not sure if I can remove my signed now...

**Comment by Aspie96** [comment]
@Mehavoid you also supported the Open Letter than changed your mind to the Support Letter?

If so what made you change your mind?

**Comment by Aspie96** [comment]
(To those searching their other signature: https://github.com/rms-open-letter/rms-open-letter.github.io/pull/1126/commits/c259a1dc7766b793a02660889e8daf47ed21b71c)

**Comment by nukeop** [comment]
> @toriningen I revised my view after signing, not sure if I can remove my signed now...

You can make a pull request here to state your intention of removing your signature:
https://github.com/rms-support-letter/revoke-open-letter-signature/

**Comment by Mehavoid** [comment]
@nukeop, thanks and done!

**Pull request merged**
