### PR TITLE
Social Media Preview: make Turkish version

### PR DESCRIPTION
**Pull request by yutyo**

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Change the `image` link here to the image https://github.com/rms-support-letter/rms-support-letter.github.io/blob/master/_translations/index_tr.md

**Comment by shenlebantongying** [comment]
I suppose `tr` is Turkish

**Comment by yutyo** [comment]
> Change the `image` link here to the image https://github.com/rms-support-letter/rms-support-letter.github.io/blob/master/_translations/index_tr.md

Done.

**Comment by shenlebantongying** [comment]
Perfect!

**Pull request merged**
