### PR TITLE
Adding xmpp chatroom on fr and en readme + discord warning

### PR DESCRIPTION
**Pull request by m-ar-c**
… fr readme

### CODE REVIEW

**Comment by shenlebantongying** [comment]
I am kind of suspect if anyone would join XMPP since chatting over discord and telegram is already visibly declined.

**Comment by nukeop** [comment]
I'm also against the warning next to our discord link, we would be doing ourselves a disservice.

**Comment by m-ar-c** [comment]
> I am kind of suspect if anyone would join XMPP since chatting over discord and telegram already visibly declined. How long you can keep the server running?

I don't know if a lot of people will join, but some already did whereas the room wasn't even public. If the room is made "official", I could also advertise it there : https://search.jabber.network/ . More people could join from there. My server is already several years old and I plan to keep it running a long time (as long as I live ^^). That being said I could understand the unwillingness to add yet another room to the list. 

> I'm also against the warning next to our discord link, we would be doing ourselves a disservice.

I don't see why it would be a disservice if 1/ people could join discord anyway, it's just a warning 2/ people could join other freedom-and-privacy-respecting rooms in the list.

I didn't propose to remove the discord channel, I think it's important people can ~~shitpost gifs and smileys~~ chat about supporting stallman in the comfort of their favorite closed source, freedom denying and spying software, if that's what they want to do.

But, don't we care enough about freedom here to at least not lure undecided or unknowing user to the discord trap ?

**Comment by nukeop** [comment]
I'm ok with adding a link to a new chatroom, but I removed the link to Stallman's page on discord, it makes us look schizophrenic and dilutes our message, I want the letter and the readme to look confident.

**Comment by m-ar-c** [comment]
I regret your decision but I understand your viewpoint. Thanks.

**Pull request merged**
