### PR TITLE
My sign

### PR DESCRIPTION
**Pull request by systemdfan**
My sign for RMS support letter

### CODE REVIEW

**Review by jobbautista9 — CHANGES_REQUESTED** [review]
Please move the file to _data/signed, otherwise the software won't be able to put your signature on the open letter.

**Comment by spaceneoduck** [comment]
Daniel Wandler 
i am support of Richard M. Stallman, he should not remove from Free Software Foundation!

**Comment by jobbautista9** [comment]
@spaceneoduck Please create a new PR for that, or comment on #837 if you want to be added. :)

**Comment by 6r1d** [comment]
I moved his file myself, it's all good.

**Comment by 6r1d** [comment]
Thank you for your support, @systemdfan!

**Pull request merged**
