### PR TITLE
Update legolivesmatter.yaml

### PR DESCRIPTION
**Pull request by LegoLivesMatter**

### CODE REVIEW

**Comment by Duncaen** [comment]
What kind of bullshit is this?

**Comment by nukeop** [comment]
What do you mean?

**Comment by Duncaen** [comment]
Signing an open letter as a "contributor" to a third party project that is not involved in this because you have 6 small commits.

**Comment by nukeop** [comment]
He is a contributor, and that's what he stated, is he not?

**Comment by Duncaen** [comment]
This is misrepresenting and dragging in a third party which has no involvement in this or any other letter.

I guess "contributor" is vaguely defined, but I'm not going to sign open letters in the name of all the projects I have written patches for a week prior and have no other involvement with.

**Comment by LegoLivesMatter** [comment]
I will only remove "Void Linux contributor" from my signature once Daniel Kolesa removes "Void Linux developer" from his signature on the other letter.

**Comment by nukeop** [comment]
Okay, @LegoLivesMatter, I would urge you to respect the wishes of Void Linux authors and remove that note from your signature. As a policy, we do not edit the signatures ourselves unless correcting the format or removing malicious content.

**Comment by Logarithmus** [comment]
> I will only remove "Void Linux contributor" from my signature once Daniel Kolesa removes "Void Linux developer" from his signature on the other letter.

I agree with you. @Duncaen & @ahesford, shame on you for using double standards: @octaforge menitioned Void in his `rms-open-letter` signature -- perfectly OK, but @LegoLivesMatter & me signing `rms-support-letter` made you so upset.

**Comment by Duncaen** [comment]
Daniel is leading the void linux ppc port, has been a long time contributor with thousands of commits and is part of the organization.

**Comment by ahesford** [comment]
There is a material difference here. The letter signed by Daniel clearly distinguishes institutional and individual signatories and even notes explicitly in the individual section that affiliations are included for identification only and do not convey endorsement by the organization.

Void takes no organizational position on matters related to Richard Stallman, and we request that signatories on either side either make it abundantly clear that their opinions are independent of the group, or that the affiliation be omitted to avoid the appearance of organizational support. 

Furthermore, as @Duncaen noted, a double standard applies because Daniel meets a higher contributory standard. His record of accomplishment and status as an official member earns him some extra liberty to attach the organization to his name than having O(10) accepted PRs.

**Comment by Logarithmus** [comment]
> Void takes no organizational position on matters related to Richard Stallman
> His record of accomplishment and status as an official member earns him some extra liberty to attach the organization to his name than having O(10) accepted PRs.

I understand that my & @LegoLivesMatter's contributions to Void are abysmal compared to @octaforge's. But I think you contradict yourself here. You said that Void organization takes no position about Stallman, but somehow @octaforge is allowed to speak on behalf of organization.
So to be consistent, we will remove mentions of Void if and only if @octaforge does the same.

P. S. Did you ask @octaforge to remove his mention of Void? I think it would be nice if you ask him to join our discussion.

**Comment by ahesford** [comment]
There is no contradiction. As I noted above, the material difference is that the anti-RMS letter not only distinguishes organizational and individual signatories, but explicitly notes that individual signatures do not convey organizational endorsement.

Daniel does not speak on behalf of Void in that matter and makes no attempt to convey that he does.

I see no such effort to make this distinction in this note, and your use of "Void Linux contributor" as **the** definitive identifier beside your name looks like an attempt to add official weight to your endorsement.

**Comment by fosslinux** [comment]
Please see on https://rms-open-letter.github.io/:

> (For individual signatures, institutional affiliation is provided for identification purposes only and does not constitute endorsement.)

Therefore it is not correct to say "but somehow @OctaForge is allowed to speak on behalf of organization"; it is explicitly stated the organization/institution (Void) is not endorsing Daniel's opinion/support of that aforementioned letter.

I do not notice any such notice on https://rms-support-letter.github.io/.

I think there is a noticeable difference being labelled as an official "Developer" (or Member in official Void terminology I believe) where you are officially registered as such (and this information is trackable in void-infrastructure) rather than a contributor with ~15 commits.

**Comment by Logarithmus** [comment]
> There is no contradiction. As I noted above, the material difference is that the anti-RMS letter not only distinguishes organizational and individual signatories, but explicitly notes that individual signatures do not convey organizational endorsement.
> 
> Daniel does not speak on behalf of Void in that matter and makes no attempt to convey that he does.
> 
> I see no such effort to make this distinction in this note, and your use of "Void Linux contributor" as **the** definitive identifier beside your name looks like an attempt to add official weight to your endorsement.

I guess that `rms-support-letter` creators can improve the letter to distinguish between individual & organizational signatures.
@nukeop, what do you think about that?

P. S. Honestly, I have a feeling that you waste time on nothing arguing about such unnecessary things. Right now I'm trying to build 5.11 kernel for armv7 & make it working on my friend's Orange Pi. When it will be finished I think it will be useful for people who, like my and my friend, want a minimal Linux without systemd & other stuff provided by Armbian on their Orange Pi.

**Comment by nukeop** [comment]
I think that if you are expressly told to remove this implied endorsement, you should do it.

**Comment by Logarithmus** [comment]
> I think that if you are expressly told to remove this implied endorsement, you should do it.

You didn't ask to my suggestion about adding "organizational" & "individual" sections to the letter.

**Comment by Logarithmus** [comment]
> Please see on https://rms-open-letter.github.io/:
> 
> > (For individual signatures, institutional affiliation is provided for identification purposes only and does not constitute endorsement.)
> 
> Therefore it is not correct to say "but somehow @OctaForge is allowed to speak on behalf of organization"; it is explicitly stated the organization/institution (Void) is not endorsing Daniel's opinion/support of that aforementioned letter.
> 
> I do not notice any such notice on https://rms-support-letter.github.io/.
> 
> I think there is a noticeable difference being labelled as an official "Developer" (or Member in official Void terminology I believe) where you are officially registered as such (and this information is trackable in void-infrastructure) rather than a contributor with ~15 commits.

OK, I guess adding notice that my signature doesn't represent the opinion of whole organization will satisfy you?

**Comment by nukeop** [comment]
> > I think that if you are expressly told to remove this implied endorsement, you should do it.
> 
> You didn't ask to my suggestion about adding "organizational" & "individual" sections to the letter.

I don't like listing organizations since those signatures are still added by individuals. Any individual is free to sign the letter with or without specifying affiliated organizations.

**Comment by paper42** [comment]
I can think of 2 reasons why you would want Void Linux next to your name:
1. for better identification
2. to give more weight to your signature

I don't see why any of these reasons should apply to you. I don't think you can be easier identified by adding "Void Linux contributor" next to your name when you have ~13 commits in a project with ~140k commits.

> I will only remove "Void Linux contributor" from my signature once Daniel Kolesa removes "Void Linux developer" from his signature on the other letter.

> My intention was to show that there are pro-Stallman people among Void contributors, not only pro-SJW ones.

Statements like these two (the first one from @LegoLivesMatter, the second one from @Logarithmus) make me think your intention is to represent Void Linux, but you deny that.

I don't think the second point applies to you, because that would imply you want to represent Void which, again, you said you don't want to.

> Honestly, I have a feeling that you waste time on nothing arguing about such unnecessary things.

I agree, just remove the mention of Void Linux from your signature, it's that simple.

Many Void contributors signed this or the other letter without needing to add "Void Linux contributor" next to their name, so I don't see a reason why you need to.

**Pull request merged**
