### PR TITLE
Sign to letter

### PR DESCRIPTION
**Pull request by teddyvn**

### CODE REVIEW

**Comment by shenlebantongying** [comment]
I think the checker has some problem,

**Comment by teddyvn** [comment]
Thanks you very much.

**Comment by 6r1d** [comment]
@teddyvn I was answering each previous PR about the same. XD

**Comment by jobbautista9** [comment]
Checker seems to be fine here. The author of the PR just haven't took the PR out of draft status.

Screenshot_2021-03-28_10-30-04

**Comment by shenlebantongying** [comment]
@teddyvn @6r1d I think the checker is checking his repo which is older than actual fix.

So we can just merge without problem.

**Comment by 6r1d** [comment]
Yeah, but the email instead of http://folami.nghelong.com seems worse.

**Comment by shenlebantongying** [comment]
@teddyvn https://github.com/rms-support-letter/rms-support-letter.github.io/blob/master/_data/signed/teddyvn.yaml

**Comment by teddyvn** [comment]
Thank you all supporters. Love you pro!

**Comment by 6r1d** [comment]
You're welcome, @teddyvn
About leaving your email in a public letter, well, it tends to attract spam bots, that's all.

**Comment by teddyvn** [comment]
@6r1d  But I tried the web address, it always says failed to deploy. I must use email address. Hikhik. I didn't know the checker had issue.

**Comment by 6r1d** [comment]
Checker had an issue with someone else's signature at the time, not yours.
I am sorry it is misleading, that's not how it should work, but that's a start.

**Pull request merged**
