### PR TITLE
Create IhorTelepenk0.yaml

### PR DESCRIPTION
**Pull request by IhorTelepenk0**

### CODE REVIEW

**Comment by jobbautista9** [comment]
Hi, any reason why you're using a different GitHub profile for your link?

**Comment by IhorTelepenk0** [comment]
> Hi, any reason why you're using a different GitHub profile for your link?

Well.., no specific reason, I just have few profiles and I was logged in from another one. I hope that's not a problem?

**Comment by jobbautista9** [comment]
Okay, but please confirm that you own that other account by commenting here using that account.

**Comment by IgorTelepenkoDev** [comment]
> Okay, but please confirm that you own that other account by commenting here using that account.

Alright, This is my account as well.

**Comment by jobbautista9** [comment]
Sorry, for the wait. Thanks for signing!

**Comment by 6r1d** [comment]
...And please consider sharing this letter in social media! :-)

**Pull request merged**
