### PR TITLE
reesericci - I am in support of rms!

### PR DESCRIPTION
**Pull request by reesericci**
I am fully in the opposition of the vile mob of hatrid that is headed at rms. It is disgusting, and I am completely in support of him returning to the FSF.

### CODE REVIEW

**Comment by oyvindsaether** [comment]
You messed up just like I did my first try. You forgot to give to give the file a .yaml extension as in 
reesericci.yaml

please try again

**Comment by reesericci** [comment]
ah

**Comment by reesericci** [comment]
ah

**Comment by reesericci** [comment]
i fixed it @oyvindsaether

**Comment by imachug** [comment]
Thanks for your support!

**Pull request merged**
