### PR TITLE
Adds a couple newlines to break scraper scripts

### PR DESCRIPTION
**Pull request by JackRedstonia**
Self-explanatory code and PR title.
I might add a couple more mechanisms to prevent scraping in the future, who knows. Have fun with this one for now.

### CODE REVIEW

**Comment by McSinyx** [comment]
But why should we prevent scraping?  This is a political statement and I doubt anyone here is ashamed of having it known to the public.

**Comment by JackRedstonia** [comment]
Think of it as an insurance policy, it simply prevents scrapers from using the letter as a vector for targeted harassment.

**Comment by shenlebantongying** [comment]
Which script are you mentioning?

I put all <li> in one line to break this one https://gist.github.com/kyhwana/73161a50d1b5019b18e3965b55a1a192

I can also track other ones.

**Comment by JackRedstonia** [comment]
@shenlebantongying I think it's the script you mentioned. Does this PR break it again?

**Comment by shenlebantongying** [comment]
No, just two different method to break it. Idc, it seems the original author already lost his interest.

There is some fun bullshit :)
https://archive.is/1bHIq

**Comment by JackRedstonia** [comment]
> It seems the original author already lost his interest.

It's still necessary to weed out the script kiddies.

**Pull request merged**
