### PR TITLE
Portuguese Social Image

### PR DESCRIPTION
**Pull request by lisbonjoker**

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Do you think if we shrink the font size of the white line, it might look better.
As least don't cover his eyes?
image

**Comment by lisbonjoker** [comment]
Done @shenlebantongying

**Comment by shenlebantongying** [comment]
Is there a reason for duplication? Maybe delete 1?
image

**Comment by lisbonjoker** [comment]
Oh sorry

**Comment by lisbonjoker** [comment]
Added that one by mistake

**Comment by shenlebantongying** [comment]
Looks nice, Thank you!

**Pull request merged**
