### PR TITLE
Create kdeligian.yaml

### PR DESCRIPTION
**Pull request by kdeligian**

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Please add a link.

**Comment by kdeligian** [comment]
I appended a new line. Could you check, please?

**Comment by shenlebantongying** [comment]
I cannot see the `link: ` line.........
image

**Comment by 6r1d** [comment]
I don't see the link in https://github.com/rms-support-letter/rms-support-letter.github.io/pull/6558/files either.

**Comment by kdeligian** [comment]
So, haven't I committed? I thought I did, but I don't know the tool anyway.
If not, do you have a  web link on how to checkout ?

 1  _data/signed/kdeligian.yaml
<https://github.com/kdeligian/rms-support-letter.github.io/commit/32abda8a79a810d96e27a1ddecc6c84e0d0ac0f1#diff-eae3d8d7d866282ef680176c5d4500063714b934738f6417c0d4cfcc4f86dba0>



@@ -1 +1,2 @@


name: Kostas Deligiannidis


link: https://github.com/kdeligian
0 comments on commit 32abda8

**Comment by 6r1d** [comment]
I applied your signature manually, @kdeligian .
https://github.com/rms-support-letter/rms-support-letter.github.io/commit/d07632592bc1b54f505e2ce95bd0966b1a38a645
Does it seem to be correct now?

**Comment by kdeligian** [comment]
I also did a Pull request that I had not done before. This time I left the
checkbox checked , so maintainers can edit.
Am I ok, with this file?

**Pull request closed without merging**
