### PR TITLE
Create jamie-ramone.yaml

### PR DESCRIPTION
**Pull request by JamieRamone**

### CODE REVIEW

**Comment by 6r1d** [comment]
Thank you for your support!
What does B.K. mean, by the way? I slightly changed your signature so it better fits the format. Alter later if you'd like.
Please share the letter on the social media, if you can.

**Comment by JamieRamone** [comment]
Big Kahuna. It's like CEO, but different...and just as meaningless. So, my signature was added? Sorry, this thing is about as complicated as the space shuttle and VS.

**Comment by 6r1d** [comment]
> Big Kahuna. It's like CEO, but different...and just as meaningless.

It's great to hear that.

> So, my signature was added?

Yes, you can find yourself as "Jamie Ramone (founder, B.K, and owner of Mondo Megagames)"! :-)

> Sorry, this thing is about as complicated as the space shuttle and VS.

I understand, and it's alright.

----

So, I guess [this pull request](https://github.com/rms-support-letter/rms-support-letter.github.io/pull/6578#event-4576159107) is not needed anymore? I won't close it myself yet.

**Comment by JamieRamone** [comment]
OK, yes, I see it now. Thanx for that! :D

Oh I created a new YAML file when this thing told me about the "missing protocol" error, as I couldn't access the original because of the directory size, which Github caps (we had million-entry ftp servers in the 56-Kbps days but it's all of a sudden a problem in the broadband age?!). Not sure what to do about it.

Also, should I just close this (re-opened) pull request or what? Sorry, I'm more of an SVN guy myself, don't really get git.

**Pull request merged**
