### PR TITLE
Add notice about not representing the whole Void

### PR DESCRIPTION
**Pull request by Logarithmus**
See https://github.com/rms-support-letter/rms-support-letter.github.io/pull/2065#issuecomment-808973364

### CODE REVIEW

**Comment by shenlebantongying** [comment]
OK.

**Comment by shenlebantongying** [comment]
You must be very important for VoidLinux i guess. Thanks for supporting us <3

**Comment by Logarithmus** [comment]
> You must be very important for VoidLinux i guess. Thanks for supporting us <3

Not as important as @q66 (his contributions are an order of magnitude more then mine), but thank you.

**Comment by Duncaen** [comment]
You don't represent the organization at all.

**Comment by sgn** [comment]
Please remove the whole affilication. The part `doesn't represent the whole organization` partly implies that you're represent part of the organization, which is false.

**Comment by shenlebantongying** [comment]
Please be kind to each other since you guys are working on the same project.

**Pull request merged**
