### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Lesik**

### CODE REVIEW

**Comment by podvornyakva** [comment]
Please. add a file instead of edit index.md

Follow README.md instructions.

Thank you.

**Comment by imachug** [comment]
Merged manually.

**Comment by Lesik** [comment]
@podvornyakva When I created this MR, the README said:

```
A open letter in support of RMS.

To sign, open a pull request. Link your profile or email in the signature. Please use a real name if possible, to maximize impact.

Let's keep the tone firm, but professional.
```

There wasn't even a folder for adding a file.

**Comment by podvornyakva** [comment]
> the repo didn't even contain a folder to put the file in

Yep. Terms was changed due massive commits errors.

**Pull request closed without merging**
